name: build-analyze-scan

on:
  push:
    branches:
      - main

jobs:
 build-analyze-scan:
    name: build
    runs-on: [self-hosted]
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: BUilding code and analyze with SonarQube
        uses: actions/checkout@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: dependencies install
        run: |
          npm install
      - name: Trivy vulnerability scan
        run: |
          trivy -fs . > trivy-report.txt

      - name: Docker build and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker build -t jackquick/zomato .
          docker tag jackquick/zomato:latest jackquick/zomato:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
          docker push jackquick/zomato:latest

      - name: Trivy scan Docker image
        run: trivy image jackquick/zomato:latest

  deploy:
    name: Deploy app to Docker
    needs: build-analyze-scan
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull jackquick/zomato:latest

      - name: Image scan with Trivy
        run: trivy image jackquick/zomato:latest > image-trivy-scan.txt

      - name: Run Docker container
        run: docker run -itd -p 3000:3000 --name zomato jackquick/zomato:latest
